### ISSUE TITLE
Cheat got detected with the newest update

### ISSUE THREAD

**Issue by Kek5chen** [DrNseven/TAB-D3D11-Hack#2]
Change Detection status to detected

**Comment by ghost** [comment]
it isnt detected its an injector issue. paste face injector or something its ud-ish. havent got banned yet

**Comment by Kek5chen** [comment]
Which injector are you using?

**Comment by ghost** [comment]
FACE Injector V2. its on here (github)

**Comment by Kek5chen** [comment]
Thanks, im gonna check that out.
