### ISSUE TITLE
How to remove the ban

### ISSUE THREAD

**Issue by DarwinYouTube** [DrNseven/TAB-D3D11-Hack#4]
Do you know how the anti-cheat works to remove the ban

**Comment by Kek5chen** [comment]
If you are banned you are banned. No going back. The bans are issued and saved server sided.

**Comment by DarwinYouTube** [comment]
I wrote a spoofer for this game and have already removed the ban, in order to understand how it works, use Process Monitor

**Comment by Kek5chen** [comment]
Wait! I know you from YT! Can you add me on Discord? I sent you a friend request. kx#9941

**Comment by Kek5chen** [comment]
Also found an error in one of your project i would like to discuss
